version: "3"
services:
    seleniumhub:
        container_name: selenium/hub:3.141.59
        image: selenium
        ports: "4444:4444"

    seleniumdriver:
        containerdriver: firefox
        image: selenium/node-firefox:3.141.59
        volume:
            - /sel-driver:/dev/shm
        depends_on:
          - seleniumhub
        environment: 
          - HUB_HOST=seleniumhub
          - HUB_PORT=4444